export * from './NombreSearch'
export * from './CheckTypeSearch'
export * from './BuscadorGeneral'
export * from './DireccionSearch'
export * from './AliasSearch'
export * from './PalacaNivSearch'
export * from './TelefonoSearch'