//Archivo de barril para importar los demas archivos de barril para importar todas las carpetas de los componentes
export * from './BuscadorFacial'
export * from './Shared'
export * from './Remision'
export * from './Inspeccion'
export * from './Historico'
export * from './Sic'
export * from './BaseMultiplier'
export * from './BuscadoGeneral'
export * from './Popover'
export * from './Graficas'
export * from './Incidencia'
export * from './Atlas'
export * from './Table'
export * from './Reportes'